# Generated by Django 3.1.5 on 2021-01-20 08:36

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(error_messages={'unique': 'Пользователь с таким номером телефона уже существует.'}, max_length=128, region=None, unique=True, verbose_name='phone'),
        ),
    ]
