# Generated by Django 3.1.5 on 2021-01-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='timer_seconds',
            field=models.SmallIntegerField(blank=True, default=120),
        ),
    ]
